### PR TITLE
Minor template and style improvement

### PR DESCRIPTION
**Pull request by gregorylegarec**
Thanks @m4dz to have a review.

This PR prepare the setup of the infos onboarding step.

* Every step was containing a `<form>` tag, even if it was not containing input or button. I used template inheritance and include to offer two base templates for steps.

* There were some incoherences with font size, width, height, etc. I made some fixes to be more compliant with @kelukeku's mockups and to mutualize code between regular steps pages and MyAccounts page.

### CODE REVIEW

**Comment by m4dz** [comment]
Sweet 👍 

If I can a suggestion, I'm not especially fan of separating concerns accross multiple templates, only because we need to wrap them in a `<form>` tag, and I ask myself if the form shouldn't be directly put in content, to ensure readability and reassembling concerns, and the footer outside of it. We just have to reference the `form` in the sumbit button using a [form attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-form), and everything will work like a charm 😃

**Comment by gregorylegarec** [comment]
@m4dz Your solution is far better, thanks for the tip !

**Comment by m4dz** [comment]
You're welcome dude

**Comment by m4dz** [comment]
Woohooo 🎉

**Pull request merged**
