### PR TITLE
Add polyfills to support Array.find and Object.assign

### PR DESCRIPTION
**Pull request by CPatchane**
Add polyfills to support Array.find and Object.assign in older browsers.
Fix tested using Chromium v42

### CODE REVIEW

**Comment by gregorylegarec** [comment]
@CPatchane Travis fails with a node4 environment. Can you investigate ?

**Comment by CPatchane** [comment]
@gregorylegarec It's fixed. Good to know: think to empty Travis caches, that can help.

**Comment by gregorylegarec** [comment]
@m4dz We discussed with @CPatchane and we think that we should use the power of webpack to handle polyfills like those ones. What your opinion ? Any recommendation ? (https://www.npmjs.com/package/webpack-polyfills-plugin ? https://www.npmjs.com/package/imports-loader ?

**Comment by m4dz** [comment]
My recommandation for polyfills: always bet on Babel 👅 

In fact, we should use `babel-preset-env` for Babel preset (wich is like an autoprefixer for Babel transpiling) and use its `useBuiltIns` directive that apply polyfills from `babel-polyfill` in the same manner (see https://github.com/babel/babel-preset-env#usebuiltins-boolean). If you want some example, I'll add it to the https://github.com/cozy/cozy-template/pull/17 tomorrow 😄

**Comment by m4dz** [comment]
After discussing, let's say we stuck on manually polyfills as we don't (yet) use Babel on the proxy. Later, when an heterogeneous codebase will come, mixing JS(X) and Coffee, we could use a `babel!coffee` loader to pass output from Coffee-Script to Babel and then use the Babel env capabilities 👍

**Comment by gregorylegarec** [comment]
Ok, so let's wait to add Babel to the project to handle polyfills with it.

I finally succeed in testing the app on browserstack with Chrome 38, it only fail at using `fetch`, so I presume the rest is OK.

**Pull request merged**
