### PR TITLE
Update app icon version with official gradient

### PR DESCRIPTION
**Pull request by m4dz**

### CODE REVIEW

**Comment by aenario** [comment]
LGTM @frankrousseau , is this the right color ?
Need build

**Comment by frankrousseau** [comment]
I'm not sure it's the right color for the proxy. Whatever, we will change the whole style soon.

**Comment by m4dz** [comment]
This is the icon for favicon/appicons, do you think the color should be different than the official one ?

**Comment by frankrousseau** [comment]
No, it's good.

**Comment by frankrousseau** [comment]
Thank you!

**Comment by m4dz** [comment]
Cool, thanks :)!

**Pull request merged**
