### PR TITLE
Fixed the way the 2FA key is being handled.

### PR DESCRIPTION
**Pull request by babolivier**
To publish at the same time than https://github.com/cozy/cozy-home/pull/771.

Fixed the way the 2FA master key is being handled by Cozy's proxy, so a Yubikey can be used to authenticate through Cozy.

Also removed an useless update which could lead to master key corruption if handled wrongly.

### CODE REVIEW

**Comment by aenario** [comment]
Hey @babolivier, could you check why Travis got red (https://travis-ci.org/cozy/cozy-proxy/jobs/145027655#L1304-L1345) ?

**Comment by babolivier** [comment]
Oops, seems like I forgot to change the test. On it as soon as I get home. Thanks for noticing @aenario.

**Comment by babolivier** [comment]
@aenario Fixed the failed test, all is green now.

**Comment by nono** [comment]
Nice!

**Pull request merged**
