### PR TITLE
[chore] clean useless build files

### PR DESCRIPTION
**Pull request by m4dz**

### CODE REVIEW

**Comment by m4dz** [comment]
@nono is this one ok for you? So We can merge it and I rebase the #246 on it to simplify the review.

**Comment by nono** [comment]
We should ask our release manager (ping @aenario). If we do so, the master and development branches will be different. In particular, the `.gitignore` file will ignore the build on development, but not in master. I'm not sure about that change.

**Comment by aenario** [comment]
That's what we have in emails and while it is a bit of hassle for merging, it avoids meaningless conflicts in development. Let's discuss in TC.

**Comment by nono** [comment]
OK, let's go for that!

**Pull request merged**
