### PR TITLE
Logo beta tag

### PR DESCRIPTION
**Pull request by m4dz**

### CODE REVIEW

**Comment by jsilvestre** [comment]
It looks good to me. @aenario I think you are the platform's TR?

**Comment by aenario** [comment]
Beta is not translated by Polyglot, but is the same world for our two language so its fine.

**Comment by aenario** [comment]
Oups, didnt notice, but the full build is 
cd client && brunch b && cd .. && cake build 

Otherwise your change dont appears when the server is started with node build/server.js as we do in production. I have completed the build.

**Comment by m4dz** [comment]
> Oups, didnt notice, but the full build is `cd client && brunch b && cd .. && cake build`

Damned! Ok, thanks for the feedback. Maybe we can have a simpliest way to do this, or is there a reason to keep those build sub-commands separated?

**Comment by jsilvestre** [comment]
It's because the build process is not normalized between apps. The most up-to-date apps have a single "cake build" command that does everything (Files has it).

**Comment by m4dz** [comment]
OK, thanks :smile:!

**Pull request merged**
